CREATE TABLE IF NOT EXISTS t_account (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    balance DECIMAL(18,2) NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0
);
