server:
  port: 8085

spring:
  application:
    name: threadlocal-practice
  banner:
    charset: UTF-8

logging:
  level:
    com.example.tl: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] - %msg%n"
